/**
 * HomeVault — Demo / POC Seed Data
 * Location: Tel Aviv, Israel (Florentin neighbourhood)
 */

export const MOCK_PROPERTY_NAME = "Florentin Apartment";

const ils = (n: number) => Math.round(n * 100);

// ─── Property ─────────────────────────────────────────────────────────────────

export const mockProperty = {
  houseName: MOCK_PROPERTY_NAME,
  houseNickname: "Florentin",
  propertyType: "Apartment",
  address: "Abarbanel St 12, Tel Aviv-Yafo, 6612421",
  latitude: "32.0580",
  longitude: "34.7699",
  purchaseDate: "2022-03-15",
  purchasePrice: ils(2_800_000),
  squareMeters: 78,
  rooms: 3,
  yearBuilt: 1965,
  floor: 3,
  parkingSpots: 0,
  hasStorage: true,
  currency: "₪",
  currencyCode: "ILS",
  timezone: "Asia/Jerusalem",
  startOfWeek: "Sunday",
  reminderDaysBefore: 7,
  mapsProvider: "google" as const,
  remindExpenses: true,
  remindLoans: true,
  remindRepairs: true,
  remindCalendar: true,
};

// ─── Expenses ─────────────────────────────────────────────────────────────────

export const mockExpenses = [
  {
    name: "Mortgage — Bank Hapoalim",
    amount: ils(8_200),
    date: "2026-04-01",
    category: "Other" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
    notes: "Loan #74-382910 · 25-year fixed · linked to prime rate",
  },
  {
    name: "Mortgage — Bank Hapoalim",
    amount: ils(8_200),
    date: "2026-03-01",
    category: "Other" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
  },
  {
    name: "Mortgage — Bank Hapoalim",
    amount: ils(8_200),
    date: "2026-02-01",
    category: "Other" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
  },
  {
    name: "Mortgage — Bank Hapoalim",
    amount: ils(8_200),
    date: "2026-01-01",
    category: "Other" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
  },
  {
    name: "Va'ad Bayit (HOA)",
    amount: ils(450),
    date: "2026-04-01",
    category: "Management" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
    notes: "Building committee fee · covers elevator, cleaning, garden, intercom",
  },
  {
    name: "Va'ad Bayit (HOA)",
    amount: ils(450),
    date: "2026-03-01",
    category: "Management" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
  },
  {
    name: "Va'ad Bayit (HOA)",
    amount: ils(450),
    date: "2026-02-01",
    category: "Management" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
  },
  {
    name: "Electricity (IEC)",
    amount: ils(315),
    date: "2026-03-15",
    category: "Utilities" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
    notes: "Israel Electric Corporation · bimonthly billed, split to monthly here",
  },
  {
    name: "Electricity (IEC)",
    amount: ils(295),
    date: "2026-02-15",
    category: "Utilities" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
  },
  {
    name: "Electricity (IEC)",
    amount: ils(345),
    date: "2026-01-15",
    category: "Utilities" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
  },
  {
    name: "Water & Sewage",
    amount: ils(175),
    date: "2026-03-01",
    category: "Utilities" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
    notes: "Tel Aviv municipality · meter reading 1st of month",
  },
  {
    name: "Water & Sewage",
    amount: ils(162),
    date: "2026-02-01",
    category: "Utilities" as const,
    isRecurring: true,
    recurringInterval: "monthly" as const,
  },
  {
    name: "Arnona Q2 2026",
    amount: ils(920),
    date: "2026-04-01",
    category: "Tax" as const,
    isRecurring: true,
    recurringInterval: "quarterly" as const,
    notes: "Tel Aviv-Yafo municipal tax · reduced rate (toshav) · due by 30 Apr",
  },
  {
    name: "Arnona Q1 2026",
    amount: ils(920),
    date: "2026-01-01",
    category: "Tax" as const,
    isRecurring: true,
    recurringInterval: "quarterly" as const,
  },
  {
    name: "Arnona Q4 2025",
    amount: ils(920),
    date: "2025-10-01",
    category: "Tax" as const,
    isRecurring: true,
    recurringInterval: "quarterly" as const,
  },
  {
    name: "Building Insurance — Clal",
    amount: ils(2_400),
    date: "2026-01-01",
    category: "Insurance" as const,
    isRecurring: true,
    recurringInterval: "yearly" as const,
    notes: "Policy #CL-2024-48821 · structure only · auto-renews Jan 1",
  },
  {
    name: "Contents & Liability Insurance — Harel",
    amount: ils(1_850),
    date: "2026-02-01",
    category: "Insurance" as const,
    isRecurring: true,
    recurringInterval: "yearly" as const,
    notes: "Home contents + personal liability · auto-renews Feb 1",
  },
  {
    name: "Plumber — kitchen drain unclogging",
    amount: ils(850),
    date: "2026-02-20",
    category: "Maintenance" as const,
    notes: "Avi Plumbing Services · 052-344-5566 · 2-hour job",
  },
  {
    name: "Electrician — new grounded outlet (kitchen)",
    amount: ils(680),
    date: "2025-12-10",
    category: "Maintenance" as const,
    notes: "Added outlet near counter for future dishwasher",
  },
  {
    name: "AC units — annual service & cleaning",
    amount: ils(480),
    date: "2025-08-25",
    category: "Maintenance" as const,
    notes: "2 units serviced before summer peak",
  },
  {
    name: "Exterior roller shutter repair",
    amount: ils(1_200),
    date: "2025-11-05",
    category: "Maintenance" as const,
    notes: "Living room shutter motor replaced · Halon Shutters Ltd",
  },
];

// ─── Repairs ──────────────────────────────────────────────────────────────────

export const mockRepairs = [
  {
    title: "Kitchen sink — slow drain after descaling",
    description: "Water drains slowly. May need pipe replacement section. Plumber did temporary fix in Feb but issue returned.",
    priority: "high" as const,
    status: "in_progress" as const,
    reportedDate: "2026-03-15",
    contractor: "Avi Plumbing Services · 052-344-5566",
    cost: ils(1_200),
    notes: "Second visit scheduled. Contractor suspects partial blockage 80cm in.",
  },
  {
    title: "Bathroom wall tiles — hairline cracks (3 tiles)",
    description: "Hairline cracks above the shower surround. Not leaking yet, but risk of water ingress if not fixed.",
    priority: "medium" as const,
    status: "open" as const,
    reportedDate: "2026-01-20",
    cost: ils(2_800),
    notes: "Got 1 quote (₪2,800). Need a second quote. Low urgency for now.",
  },
  {
    title: "Water heater — pressure drop when multiple taps open",
    description: "Hot water pressure drops noticeably when shower and kitchen tap are both open. Likely mixing valve.",
    priority: "medium" as const,
    status: "waiting_for_parts" as const,
    reportedDate: "2025-12-01",
    contractor: "Avi Plumbing Services · 052-344-5566",
    cost: ils(900),
    notes: "Contractor said it's likely the pressure-balancing valve. Parts on order.",
  },
  {
    title: "AC outdoor unit — unusual noise when starting",
    description: "Compressor makes a grinding sound for the first 30 seconds when starting from off. Worse in cold mornings.",
    priority: "low" as const,
    status: "open" as const,
    reportedDate: "2026-02-10",
    cost: ils(1_500),
    notes: "Technician visit booked for May service — will diagnose then.",
  },
  {
    title: "Master bedroom door — stiff latch",
    description: "Latch didn't retract smoothly, sometimes jammed.",
    priority: "low" as const,
    status: "completed" as const,
    reportedDate: "2025-10-05",
    cost: ils(180),
    notes: "Replaced latch mechanism. Works fine now.",
  },
  {
    title: "Balcony — water seepage into ceiling below",
    description: "Water stain appeared on ceiling of ground-floor storage after heavy rain. Traced to balcony membrane failure.",
    priority: "high" as const,
    status: "completed" as const,
    reportedDate: "2025-09-01",
    contractor: "Roni Waterproofing Ltd · 054-778-2233",
    cost: ils(4_800),
    notes: "Applied new bitumen membrane + drainage mat. 5-year workmanship warranty.",
  },
];

// ─── Upgrades ─────────────────────────────────────────────────────────────────

export const mockUpgrades = [
  {
    title: "Kitchen renovation",
    description: "Full gut-and-replace: new cabinets (Egger board), quartz countertop (Caesarstone Statuario), undermount sink, and backsplash tiles.",
    status: "in_progress" as const,
    estimatedCost: ils(48_000),
    actualCost: ils(29_500),
    notes: "Countertop delivery ETA May 8 — Rami can only start installation after it arrives.",
    options: [
      {
        title: "IKEA + Rami Installation",
        estimatedCost: ils(17_100),
        description: "IKEA Metod cabinets supply, handles, full installation by Rami.",
        selected: true,
        notes: "Very professional. Phone: 052-344-1188",
      },
      {
        title: "Yossi Cabinets",
        estimatedCost: ils(16_200),
        description: "Custom cabinets + installation. Countertop and handles excluded.",
        selected: false,
        notes: "Phone: 054-221-8800",
      },
      {
        title: "Local Carpenter (Shlomo)",
        estimatedCost: ils(19_800),
        description: "All-inclusive: custom cabinets, countertop, handles, installation.",
        selected: false,
        notes: "Phone: 050-987-6543",
      },
    ],
    items: [
      { name: "Kitchen cabinets (IKEA Metod)", store: "IKEA", estimatedCost: ils(8_400), actualCost: ils(8_100), purchased: true },
      { name: "Backsplash tiles (Porcelanosa, 30×60)", store: "Porcelanosa", estimatedCost: ils(3_600), actualCost: ils(3_400), purchased: true },
      { name: "Cabinet handles ×24 (IKEA Eneryda)", store: "IKEA", estimatedCost: ils(400), actualCost: ils(380), purchased: true },
      { name: "Plumber — pipe relocation", store: "Avi Plumbing", estimatedCost: ils(1_800), actualCost: ils(1_800), purchased: true },
      { name: "Countertop — Caesarstone Statuario", store: "Caesarstone", estimatedCost: ils(4_200), purchased: false, notes: "ETA May 8" },
      { name: "LED strip under cabinets (5m)", store: "Amazon", estimatedCost: ils(280), purchased: false },
      { name: "Undermount sink (Franke MRG 110-52)", estimatedCost: ils(1_100), purchased: false },
      { name: "Kitchen faucet (pull-out spray)", estimatedCost: ils(600), purchased: false },
      { name: "Built-in oven (60cm)", estimatedCost: ils(3_200), purchased: false },
    ],
  },
  {
    title: "Main bathroom retiling",
    description: "Remove all existing wall + floor tiles. Lay 60×60 large-format porcelain (Atlas Concorde).",
    status: "planning" as const,
    estimatedCost: ils(22_000),
    actualCost: 0,
    notes: "Starting after kitchen is fully done.",
    options: [
      {
        title: "Roni Tiling Works",
        estimatedCost: ils(20_000),
        description: "Full demo, waterproofing membrane, wall + floor tiles. Timeline: 3 weeks.",
        selected: false,
        notes: "Phone: 052-771-4490",
      },
      {
        title: "Dan Renovations",
        estimatedCost: ils(24_500),
        description: "Full demo, waterproofing, wall + floor tiles, vanity included. Timeline: 2.5 weeks.",
        selected: false,
        notes: "Phone: 054-882-3311",
      },
    ],
    items: [
      { name: "Floor tiles — Atlas Concorde 60×60 (7 sqm)", store: "Porcelanosa", estimatedCost: ils(3_200), purchased: false },
      { name: "Wall tiles — Atlas Concorde 30×60 (18 sqm)", store: "Porcelanosa", estimatedCost: ils(2_800), purchased: false },
      { name: "IKEA Godmorgon vanity 80cm (white)", store: "IKEA", estimatedCost: ils(2_400), purchased: false },
      { name: "Shower mixer (Grohe Euphoria)", estimatedCost: ils(1_800), purchased: false },
      { name: "Toilet (Roca Meridian)", estimatedCost: ils(1_600), purchased: false },
      { name: "Towel rail — heated electric", estimatedCost: ils(900), purchased: false },
    ],
  },
  {
    title: "Smart lighting — Shelly relays",
    description: "Replace all switches with Shelly 1PM relays. Google Home integration.",
    status: "in_progress" as const,
    estimatedCost: ils(4_500),
    actualCost: ils(1_120),
    notes: "Shelly relays delivered. Electrician booked for May 15.",
    options: [
      {
        title: "DIY + Electrician (Eli)",
        estimatedCost: ils(1_800),
        description: "Eli installs 8x Shelly relays + wires to existing switches.",
        selected: true,
        notes: "Phone: 053-600-1234",
      },
    ],
    items: [
      { name: "Shelly 1PM relays ×8", store: "AliExpress", estimatedCost: ils(1_120), actualCost: ils(1_120), purchased: true },
      { name: "Electrician labour (Eli)", store: "Eli Electric", estimatedCost: ils(1_800), purchased: false },
      { name: "Switch cover plates ×8 (white)", estimatedCost: ils(240), purchased: false },
    ],
  },
  {
    title: "Hallway built-in storage",
    description: "Custom floor-to-ceiling wardrobe in entrance hallway (2.4m wide).",
    status: "completed" as const,
    estimatedCost: ils(8_500),
    actualCost: ils(8_200),
    notes: "Completed April 2025. Very satisfied with result.",
    options: [
      {
        title: "Yossi Amsalem Carpentry",
        estimatedCost: ils(8_200),
        description: "Custom melamine wardrobe, push-to-open hinges, full installation.",
        selected: true,
        notes: "Excellent work. Phone: 050-432-1188",
      },
    ],
    items: [
      { name: "Custom wardrobe unit (2.4m)", store: "Yossi Amsalem", estimatedCost: ils(7_800), actualCost: ils(7_800), purchased: true },
      { name: "Push-to-open hinges ×6 (Blum)", estimatedCost: ils(280), actualCost: ils(280), purchased: true },
      { name: "Internal shelving hardware", estimatedCost: ils(120), actualCost: ils(120), purchased: true },
    ],
  },
];

// ─── Loans ────────────────────────────────────────────────────────────────────

export const mockLoans = [
  {
    name: "Family Loan — Parents",
    lender: "Abba & Ima (Parents)",
    originalAmount: ils(150_000),
    currentBalance: ils(80_000),
    interestRate: "0.00",
    loanType: "other" as const,
    startDate: "2022-02-01",
    endDate: "2027-02-01",
    notes: "Down-payment supplement. Repaid so far: ₪70,000 · Outstanding: ₪80,000",
  },
];

// ─── Wishlist ─────────────────────────────────────────────────────────────────

export const mockWishlist = [
  {
    name: "Split AC — bedroom 2",
    estimatedPrice: ils(6_500),
    priority: "high" as const,
    category: "Appliance" as const,
  },
  {
    name: "Dishwasher (Bosch Series 4, 60cm)",
    estimatedPrice: ils(3_800),
    priority: "high" as const,
    category: "Appliance" as const,
  },
  {
    name: "Robot vacuum (Roborock S8 Pro)",
    estimatedPrice: ils(2_400),
    priority: "medium" as const,
    category: "Appliance" as const,
  },
  {
    name: "Mamad (safe room) shelving",
    estimatedPrice: ils(1_100),
    priority: "low" as const,
    category: "Other" as const,
  },
  {
    name: "Electric scooter (Xiaomi Pro 2)",
    estimatedPrice: ils(4_200),
    priority: "medium" as const,
    category: "Other" as const,
  },
];

// ─── Purchase Costs ───────────────────────────────────────────────────────────

export const mockPurchaseCosts = [
  {
    name: "Real estate agent fee",
    amount: ils(56_000),
    date: "2022-03-15",
    category: "Agency" as const,
    notes: "Standard 2% buyer-side agent fee",
  },
  {
    name: "Mas Rechisha (purchase tax)",
    amount: ils(38_500),
    date: "2022-04-10",
    category: "Tax" as const,
    notes: "First-apartment reduced-rate bracket · paid via lawyer to tax authority",
  },
  {
    name: "Lawyer fee — conveyancing (Adv. Michal Levi)",
    amount: ils(9_200),
    date: "2022-03-28",
    category: "Legal" as const,
    notes: "Includes purchase agreement, title search, and tabu registration",
  },
  {
    name: "Mortgage registration — Land Registry (tabu)",
    amount: ils(1_380),
    date: "2022-05-02",
    category: "Legal" as const,
    notes: "Bank lien registration with Israel Land Authority",
  },
  {
    name: "Bank appraisal (shuma)",
    amount: ils(2_500),
    date: "2022-02-20",
    category: "Other" as const,
    notes: "Bank Hapoalim-required valuation before mortgage approval",
  },
  {
    name: "Moving company (Rahav Moving)",
    amount: ils(4_800),
    date: "2022-05-20",
    category: "Moving" as const,
    notes: "Full-service move from Ramat Gan · 5-hour job including packing",
  },
  {
    name: "Locksmith — new cylinders (3 locks)",
    amount: ils(1_200),
    date: "2022-05-21",
    category: "Other" as const,
    notes: "Replaced all door lock cylinders on move-in day",
  },
];

// ─── Calendar Events ──────────────────────────────────────────────────────────

export const mockCalendarEvents = [
  {
    title: "Arnona Q2 payment due",
    date: "2026-04-30",
    category: "Payment" as const,
    notes: "Pay before April 30 to avoid late fee.",
  },
  {
    title: "Kitchen countertop delivery (Caesarstone)",
    date: "2026-05-08",
    category: "Renovation" as const,
    notes: "Must be home 08:00–12:00. Clear path from elevator to kitchen.",
  },
  {
    title: "AC annual service — pre-summer",
    date: "2026-05-20",
    category: "Maintenance" as const,
    notes: "Call Roma AC (054-123-4567) to confirm appointment. Both units.",
  },
  {
    title: "Va'ad Bayit annual meeting",
    date: "2026-06-10",
    category: "Other" as const,
    notes: "Building committee meeting. Elevator renovation budget vote. Time: 19:00.",
  },
  {
    title: "Parents loan repayment",
    date: "2026-06-01",
    category: "Payment" as const,
    notes: "Planned ₪15,000 transfer. Outstanding balance will be ₪65,000 after.",
  },
  {
    title: "Building insurance renewal (Clal)",
    date: "2027-01-01",
    category: "Payment" as const,
    notes: "Get 2 competing quotes in December before auto-renewal date.",
  },
];

// ─── Inventory ────────────────────────────────────────────────────────────────
//
// category enum: "Appliance" | "Furniture" | "Electronics" | "Consumable" |
//                "Tool" | "Valuable" | "Other"
// condition enum: "New" | "Good" | "Fair" | "Poor"

export const mockInventory = [
  // ── Appliances ────────────────────────────────────────────────────────────
  {
    name: "Samsung Washing Machine WW80T",
    category: "Appliance" as const,
    room: "Utility",
    quantity: 1,
    purchasePrice: ils(3_200),
    purchaseDate: "2022-05-25",
    brand: "Samsung",
    condition: "Good" as const,
    warrantyExpiry: "2027-05-25",
    notes: "8kg drum · 1400 RPM · purchased from KSP Tel Aviv",
  },
  {
    name: "Bosch Refrigerator KGN36",
    category: "Appliance" as const,
    room: "Kitchen",
    quantity: 1,
    purchasePrice: ils(4_100),
    purchaseDate: "2022-05-25",
    brand: "Bosch",
    condition: "Good" as const,
    warrantyExpiry: "2027-05-25",
    notes: "NoFrost · 321L · model KGN36VLED",
  },
  {
    name: "Electra Split AC 12000 BTU",
    category: "Appliance" as const,
    room: "Living Room",
    quantity: 1,
    purchasePrice: ils(3_800),
    purchaseDate: "2022-06-10",
    brand: "Electra",
    condition: "Good" as const,
    warrantyExpiry: "2027-06-10",
    notes: "Inverter · serviced Aug 2025",
  },
  {
    name: "Electra Split AC 9000 BTU",
    category: "Appliance" as const,
    room: "Bedroom",
    quantity: 1,
    purchasePrice: ils(2_900),
    purchaseDate: "2022-06-10",
    brand: "Electra",
    condition: "Good" as const,
    warrantyExpiry: "2027-06-10",
    notes: "Inverter · master bedroom",
  },
  {
    name: "Ariston Water Heater 60L",
    category: "Appliance" as const,
    room: "Utility",
    quantity: 1,
    purchasePrice: ils(1_400),
    purchaseDate: "2023-01-15",
    brand: "Ariston",
    condition: "Fair" as const,
    notes: "Pressure drop issue under investigation — see repair log",
  },
  {
    name: "DeLonghi Espresso Machine EC685",
    category: "Appliance" as const,
    room: "Kitchen",
    quantity: 1,
    purchasePrice: ils(1_100),
    purchaseDate: "2023-03-20",
    brand: "DeLonghi",
    condition: "Good" as const,
  },
  // ── Electronics ───────────────────────────────────────────────────────────
  {
    name: "LG OLED TV 55\" C3",
    category: "Electronics" as const,
    room: "Living Room",
    quantity: 1,
    purchasePrice: ils(6_200),
    purchaseDate: "2023-11-24",
    brand: "LG",
    condition: "New" as const,
    warrantyExpiry: "2026-11-24",
    notes: "Black Friday deal · model OLED55C34LA",
  },
  {
    name: "Google Nest Hub (2nd Gen)",
    category: "Electronics" as const,
    room: "Kitchen",
    quantity: 1,
    purchasePrice: ils(420),
    purchaseDate: "2024-02-10",
    brand: "Google",
    condition: "Good" as const,
    notes: "Smart home hub · controls Shelly relays and AC via Google Home",
  },
  {
    name: "Shelly 1PM Smart Relay",
    category: "Electronics" as const,
    room: "Utility",
    quantity: 8,
    minQuantity: 0,
    purchasePrice: ils(140),
    purchaseDate: "2026-04-01",
    brand: "Shelly",
    condition: "New" as const,
    notes: "For smart lighting upgrade — awaiting electrician installation May 15",
    tags: ["smart-home", "lighting"],
  },
  // ── Furniture ─────────────────────────────────────────────────────────────
  {
    name: "IKEA Kivik Sofa (3-seat)",
    category: "Furniture" as const,
    room: "Living Room",
    quantity: 1,
    purchasePrice: ils(3_100),
    purchaseDate: "2022-06-01",
    brand: "IKEA",
    condition: "Good" as const,
    store: "IKEA Rishon LeZion",
  },
  {
    name: "IKEA Malm Bed Frame (160cm)",
    category: "Furniture" as const,
    room: "Bedroom",
    quantity: 1,
    purchasePrice: ils(1_400),
    purchaseDate: "2022-06-01",
    brand: "IKEA",
    condition: "Good" as const,
    store: "IKEA Rishon LeZion",
  },
  {
    name: "Hallway Built-in Wardrobe",
    category: "Furniture" as const,
    room: "Hallway",
    quantity: 1,
    purchasePrice: ils(8_200),
    purchaseDate: "2025-04-15",
    brand: "Yossi Amsalem Carpentry",
    condition: "New" as const,
    notes: "Custom 2.4m floor-to-ceiling · melamine · push-to-open hinges",
  },
  // ── Consumables ───────────────────────────────────────────────────────────
  {
    name: "Water Filter Cartridges (Omnipure)",
    category: "Consumable" as const,
    room: "Kitchen",
    quantity: 2,
    minQuantity: 1,
    unit: "pcs",
    purchasePrice: ils(85),
    brand: "Omnipure",
    condition: "New" as const,
    notes: "Replace every 6 months · last replaced Jan 2026",
    tags: ["maintenance"],
  },
  {
    name: "AC Filter Replacements",
    category: "Consumable" as const,
    room: "Utility",
    quantity: 4,
    minQuantity: 2,
    unit: "pcs",
    purchasePrice: ils(45),
    condition: "New" as const,
    notes: "For both Electra units · clean/replace every season",
    tags: ["maintenance"],
  },
  // ── Tools ─────────────────────────────────────────────────────────────────
  {
    name: "Bosch PSB 1800 LI-2 Drill",
    category: "Tool" as const,
    room: "Mamad",
    quantity: 1,
    purchasePrice: ils(620),
    purchaseDate: "2022-07-01",
    brand: "Bosch",
    condition: "Good" as const,
    notes: "18V cordless · comes with 2 batteries",
  },
  {
    name: "Tool Kit (screwdrivers, pliers, wrench set)",
    category: "Tool" as const,
    room: "Mamad",
    quantity: 1,
    purchasePrice: ils(380),
    purchaseDate: "2022-05-22",
    condition: "Good" as const,
    notes: "Stanley 94-piece set",
  },
  // ── Valuables ─────────────────────────────────────────────────────────────
  {
    name: "Trek FX3 Bicycle",
    category: "Valuable" as const,
    room: "Mamad",
    quantity: 1,
    purchasePrice: ils(4_500),
    purchaseDate: "2023-05-01",
    brand: "Trek",
    condition: "Good" as const,
    serialNumber: "WTU219B04321",
    notes: "Registered with Tel Aviv bike registry · insured under Harel contents policy",
  },
];
