name: Build & Publish Home Assistant Add-on

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ADDON_PATH: homevault-addon

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, aarch64, armv7]
    permissions:

      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Normalize image repository name
        run: echo "REPOSITORY_LC=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.ADDON_PATH }}/Dockerfile
          platforms: linux/${{ matrix.arch == 'armv7' && 'arm/v7' || matrix.arch }}
          push: true
          build-args: |
            BUILD_ARCH=${{ matrix.arch }}
          tags: |
            tags: |
              ghcr.io/${{ env.REPOSITORY_LC }}-addon-${{ matrix.arch }}:latest
              ghcr.io/${{ env.REPOSITORY_LC }}-addon-${{ matrix.arch }}:${{ github.sha }}
              ghcr.io/${{ env.REPOSITORY_LC }}-addon-${{ matrix.arch }}:0.1.4
